name: Github Actions CI/CD Pipeline

on: push

env:
  AWS_REGION: eu-south-2
  ECR_REPOSITORY: 181053172120.dkr.ecr.eu-south-2.amazonaws.com

jobs:
  build-job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: techwave-app
    strategy:
      fail-fast: false
      matrix:
        node: [ 20, 22, 24 ]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Setup Node.js environment
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
          cache-dependency-path: techwave-app/package-lock.json

      - name: Install Dependencies
        run: npm ci
        
      - name: Run Unit Tests
        run: echo "Running tests..." && npm test
  
  sonarqube:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
      with:
        fetch-depth: 0

    - name: SonarQube Scan
      run: echo "Running SonarQube scan..." 

  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v3

  docker:
    needs: [build-job, sonarqube, gitleaks]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      id-token: write  
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build docker image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ env.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
        run: docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
      
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
          format: table
          exit-code: '1'    
          ignore-unfixed: true   
          vuln-type: 'os,library'   
          severity: CRITICAL,HIGH
      
      - name: Push docker image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ env.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
        run: docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG